# This is a basic workflow to help you get started with Actions
name: Run Unit Tests
"on": push
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
              npm install
              npm run test:unit
